### PR TITLE
GlfwWindow reforged to make possible multi-windowing 

### PR DESCRIPTION
**Pull request by allcreater**
Glfw guides requires that functions such as glfwPollEvents should be called from main thread only so that now main cycle moved to global Glfw singletone

### CODE REVIEW

**Comment by NukeBird** [comment]
I see you moved GLFW_INCLUDE_NONE to CMakeLists - yeah that's a great idea

If talking about window wrapper - I can't really say much because this thing does its job (wraps GLFW functionality) 

GlfwApplication::get() singleton thread-safe until default GlfwApplication ctor is safe, no problems here

You can add extra validation to things like glfwWindowHint (this func can generate GLFW_INVALID_ENUM in case of illegal arguments) but in my opinion it's not so important

**Comment by NukeBird** [comment]
Take a look at glfwDefaultWindowHints

**Comment by allcreater** [comment]
> You can add extra validation to things like glfwWindowHint (this func can generate GLFW_INVALID_ENUM in case of illegal arguments) but in my opinion it's not so important

It seems we already have error handling with glfwSetErrorCallback that should throw an exception with error description :)

**Comment by NukeBird** [comment]
alrighty then

**Pull request merged**
